export const PROJECTS = [
  {
    name: "Office Building",
    type: "office",
    levels: 3,
    zonesPerLevel: 6,
    summary: "Office building",
    trades: [
      { key: "framing", name: "Framing", color: "#7d8790", baseCost: 1750 },
      {
        key: "electrical",
        name: "Electrical",
        color: "#f3c537",
        baseCost: 1680,
      },
      { key: "plumbing", name: "Plumbing", color: "#2388d1", baseCost: 1700 },
      { key: "drywall", name: "Drywall", color: "#d8d2c6", baseCost: 1620 },
      { key: "painting", name: "Painting", color: "#78b7e8", baseCost: 1500 },
      { key: "finishes", name: "Finishes", color: "#55a85f", baseCost: 1850 },
    ],
  },
  {
    name: "Hospital Buildout",
    type: "hospital",
    levels: 4,
    zonesPerLevel: 6,
    summary: "Hospital project",
    trades: [
      { key: "framing", name: "Framing", color: "#7d8790", baseCost: 1850 },
      { key: "plumbing", name: "Plumbing", color: "#2388d1", baseCost: 1950 },
      {
        key: "electrical",
        name: "Electrical",
        color: "#f3c537",
        baseCost: 1880,
      },
      { key: "hvac", name: "HVAC", color: "#56c0c9", baseCost: 2050 },
      {
        key: "fire",
        name: "Fire Protection",
        color: "#e84f3d",
        baseCost: 1900,
      },
      { key: "drywall", name: "Drywall", color: "#d8d2c6", baseCost: 1720 },
      {
        key: "cleanroom",
        name: "Cleanroom Finishes",
        color: "#a8e7f0",
        baseCost: 2100,
      },
      {
        key: "equipment",
        name: "Equipment Install",
        color: "#b07ad8",
        baseCost: 2300,
      },
    ],
  },
  {
    name: "Data Center",
    type: "data-center",
    levels: 1,
    zonesPerLevel: 30,
    zoneColumns: 6,
    summary: "Data center level",
    trades: [
      {
        key: "raised-floor",
        name: "Structure / Raised Floor Prep",
        color: "#8a97a3",
        baseCost: 2100,
      },
      {
        key: "power",
        name: "Electrical Distribution",
        color: "#ffd84d",
        baseCost: 2250,
      },
      {
        key: "backup-power",
        name: "Backup Power",
        color: "#ff8a2a",
        baseCost: 2450,
      },
      {
        key: "cooling",
        name: "Cooling Infrastructure",
        color: "#32c7dc",
        baseCost: 2350,
      },
      {
        key: "data-cabling",
        name: "Data Cabling",
        color: "#7d7cff",
        baseCost: 2050,
      },
      {
        key: "rack-install",
        name: "Server Rack Installation",
        color: "#4f6170",
        baseCost: 2200,
      },
      {
        key: "server-equipment",
        name: "Server Equipment Installation",
        color: "#2fd17c",
        baseCost: 2550,
      },
      {
        key: "commissioning",
        name: "Commissioning / Testing",
        color: "#d66dff",
        baseCost: 2400,
      },
    ],
  },
  {
    name: "Wind Farm",
    type: "wind-farm",
    levels: 1,
    zonesPerLevel: 20,
    zoneColumns: 5,
    summary: "Wind farm field",
    trades: [
      {
        key: "access-roads",
        name: "Access Roads",
        color: "#b9975b",
        baseCost: 1800,
      },
      {
        key: "turbine-foundation",
        name: "Turbine Foundations",
        color: "#8d9298",
        baseCost: 2100,
      },
      {
        key: "tower-erection",
        name: "Tower Erection",
        color: "#d7dde4",
        baseCost: 2350,
      },
      {
        key: "nacelle-install",
        name: "Nacelle Installation",
        color: "#8bc4ff",
        baseCost: 2450,
      },
      {
        key: "blade-install",
        name: "Blade Installation",
        color: "#f5f7fb",
        baseCost: 2550,
      },
      {
        key: "collection-cabling",
        name: "Collection Cabling",
        color: "#ffcf4d",
        baseCost: 2050,
      },
      {
        key: "substation",
        name: "Substation Tie-In",
        color: "#b583e8",
        baseCost: 2300,
      },
      {
        key: "wind-commissioning",
        name: "Commissioning",
        color: "#4ac77b",
        baseCost: 2200,
      },
    ],
  },
  {
    name: "Housing Development",
    type: "housing",
    levels: 1,
    zonesPerLevel: 24,
    zoneColumns: 6,
    summary: "Housing development",
    trades: [
      { key: "sitework", name: "Sitework", color: "#9b7a4d", baseCost: 1900 },
      { key: "utilities", name: "Utilities", color: "#2f9dd6", baseCost: 2000 },
      {
        key: "slab-foundation",
        name: "Slab Foundations",
        color: "#8d9298",
        baseCost: 2100,
      },
      {
        key: "house-framing",
        name: "House Framing",
        color: "#c58a4a",
        baseCost: 2150,
      },
      { key: "roofing", name: "Roofing", color: "#7f4f3a", baseCost: 2050 },
      {
        key: "mep-rough",
        name: "MEP Rough-In",
        color: "#f3c537",
        baseCost: 2200,
      },
      { key: "drywall", name: "Drywall", color: "#d8d2c6", baseCost: 1900 },
      {
        key: "home-finishes",
        name: "Home Finishes",
        color: "#6bbf6f",
        baseCost: 2250,
      },
    ],
  },
  {
    name: "Solar Farm",
    type: "solar-farm",
    levels: 1,
    zonesPerLevel: 30,
    zoneColumns: 6,
    summary: "Solar farm array",
    trades: [
      {
        key: "access-roads",
        name: "Access Roads",
        color: "#b9975b",
        baseCost: 1800,
      },
      {
        key: "pile-driving",
        name: "Pile Driving",
        color: "#8d9298",
        baseCost: 2050,
      },
      {
        key: "solar-racking",
        name: "Racking",
        color: "#6f8796",
        baseCost: 2150,
      },
      {
        key: "solar-panels",
        name: "Panel Install",
        color: "#1d5f9f",
        baseCost: 2300,
      },
      {
        key: "collection-cabling",
        name: "DC Cabling",
        color: "#ffcf4d",
        baseCost: 2050,
      },
      { key: "inverters", name: "Inverters", color: "#b583e8", baseCost: 2250 },
      {
        key: "grid-tie",
        name: "Grid Tie-In",
        color: "#ff8a2a",
        baseCost: 2350,
      },
      {
        key: "solar-commissioning",
        name: "Commissioning",
        color: "#4ac77b",
        baseCost: 2200,
      },
    ],
  },
  {
    name: "Airport Expansion",
    type: "airport",
    levels: 1,
    zonesPerLevel: 25,
    zoneColumns: 5,
    summary: "Airport expansion",
    trades: [
      { key: "earthwork", name: "Earthwork", color: "#9b7a4d", baseCost: 2050 },
      {
        key: "paving",
        name: "Runway Paving",
        color: "#5a6066",
        baseCost: 2350,
      },
      {
        key: "terminal-structure",
        name: "Terminal Structure",
        color: "#7d8790",
        baseCost: 2450,
      },
      {
        key: "baggage",
        name: "Baggage Systems",
        color: "#32c7dc",
        baseCost: 2250,
      },
      {
        key: "jet-bridges",
        name: "Jet Bridges",
        color: "#8bc4ff",
        baseCost: 2400,
      },
      {
        key: "electrical",
        name: "Airfield Electrical",
        color: "#f3c537",
        baseCost: 2300,
      },
      {
        key: "security-systems",
        name: "Security Systems",
        color: "#d66dff",
        baseCost: 2200,
      },
      {
        key: "airport-commissioning",
        name: "Commissioning",
        color: "#4ac77b",
        baseCost: 2300,
      },
    ],
  },
  {
    name: "Hotel Sitework",
    type: "hotel-site",
    levels: 1,
    zonesPerLevel: 24,
    zoneColumns: 6,
    summary: "Hotel dirt work, utilities, and foundations",
    trades: [
      { key: "earthwork", name: "Dirt Work", color: "#9b7a4d", baseCost: 2150 },
      {
        key: "underground",
        name: "Underground Utilities",
        color: "#2388d1",
        baseCost: 2250,
      },
      {
        key: "deep-foundations",
        name: "Deep Foundations",
        color: "#8d9298",
        baseCost: 2450,
      },
      {
        key: "slab-foundation",
        name: "Grade Beams / Slabs",
        color: "#b8bcc0",
        baseCost: 2350,
      },
      {
        key: "waterproofing",
        name: "Waterproofing",
        color: "#32c7dc",
        baseCost: 2100,
      },
      {
        key: "utility-tie",
        name: "Utility Tie-Ins",
        color: "#f3c537",
        baseCost: 2250,
      },
      {
        key: "site-inspection",
        name: "Site Inspection",
        color: "#4ac77b",
        baseCost: 2000,
      },
    ],
  },
  {
    name: "Hotel Structure and Skin",
    type: "hotel-structure",
    levels: 6,
    zonesPerLevel: 6,
    summary: "Hotel structure and skin",
    trades: [
      { key: "structure", name: "Structure", color: "#7d8790", baseCost: 2450 },
      { key: "skin", name: "Exterior Skin", color: "#78b7e8", baseCost: 2350 },
      { key: "roofing", name: "Roofing", color: "#7f4f3a", baseCost: 2200 },
      { key: "elevators", name: "Elevators", color: "#b583e8", baseCost: 2550 },
      {
        key: "mep-rough",
        name: "MEP Risers",
        color: "#f3c537",
        baseCost: 2400,
      },
      {
        key: "fire",
        name: "Fire Protection",
        color: "#e84f3d",
        baseCost: 2250,
      },
      {
        key: "skin-inspection",
        name: "Envelope Inspection",
        color: "#4ac77b",
        baseCost: 2050,
      },
    ],
  },
  {
    name: "Hotel Interior Finishes",
    type: "hotel-interiors",
    levels: 6,
    zonesPerLevel: 6,
    summary: "Hotel interior finishes",
    trades: [
      {
        key: "framing",
        name: "Interior Framing",
        color: "#7d8790",
        baseCost: 2150,
      },
      {
        key: "guestroom-mep",
        name: "Guestroom MEP",
        color: "#f3c537",
        baseCost: 2350,
      },
      { key: "drywall", name: "Drywall", color: "#d8d2c6", baseCost: 2050 },
      { key: "tile", name: "Tile / Baths", color: "#78b7e8", baseCost: 2250 },
      {
        key: "painting",
        name: "Paint / Wallcovering",
        color: "#b8a5e6",
        baseCost: 2050,
      },
      { key: "ff-e", name: "FF&E", color: "#6bbf6f", baseCost: 2450 },
      { key: "amenities", name: "Amenities", color: "#ffcf4d", baseCost: 2350 },
      {
        key: "final-inspection",
        name: "Final Inspection",
        color: "#4ac77b",
        baseCost: 2150,
      },
    ],
  },
];

const TRADE_COLOR_OVERRIDES = {
  framing: "#7D8485",
  structure: "#7D8485",
  electrical: "#F4C95D",
  power: "#F4C95D",
  "backup-power": "#ED6C02",
  plumbing: "#2196F3",
  utilities: "#2196F3",
  drywall: "#D7E3EA",
  painting: "#64B5F6",
  finishes: "#4CAF50",
  hvac: "#42A5F5",
  fire: "#E85D4F",
  cleanroom: "#BBDEFB",
  equipment: "#8E78D6",
  "raised-floor": "#8FA1AA",
  cooling: "#42A5F5",
  "data-cabling": "#5C6BC0",
  "rack-install": "#626B6C",
  "server-equipment": "#4CAF50",
  commissioning: "#8E78D6",
  "wind-commissioning": "#4CAF50",
  "solar-commissioning": "#4CAF50",
  "final-inspection": "#4CAF50",
  "skin-inspection": "#4CAF50",
  "access-roads": "#B8955B",
  sitework: "#B8955B",
  earthwork: "#B8955B",
  "turbine-foundation": "#8FA1AA",
  "slab-foundation": "#8FA1AA",
  "pile-driving": "#8FA1AA",
  "tower-erection": "#D7E3EA",
  "nacelle-install": "#BBDEFB",
  "blade-install": "#F7FAFC",
  "collection-cabling": "#F4C95D",
  substation: "#8E78D6",
  "house-framing": "#C99555",
  roofing: "#A66A4A",
  "mep-rough": "#F4C95D",
  "home-finishes": "#66BB6A",
  "solar-racking": "#7D8485",
  "solar-panels": "#1976D2",
  inverters: "#8E78D6",
  "grid-tie": "#ED6C02",
  "site-grading": "#626B6C",
  "site-utilities": "#2196F3",
  paving: "#626B6C",
  "terminal-structure": "#7D8485",
  baggage: "#42A5F5",
  "jet-bridges": "#BBDEFB",
  "runway-lighting": "#F4C95D",
  "security-systems": "#8E78D6",
  "systems-testing": "#8E78D6",
  "airport-commissioning": "#4CAF50",
  underground: "#2196F3",
  "deep-foundations": "#8FA1AA",
  waterproofing: "#42A5F5",
  "utility-tie": "#F4C95D",
  "site-inspection": "#4CAF50",
  skin: "#64B5F6",
  elevators: "#8E78D6",
  "guestroom-mep": "#F4C95D",
  tile: "#64B5F6",
  "ff-e": "#66BB6A",
  amenities: "#F4C95D",
};

PROJECTS.forEach((project) => {
  project.trades.forEach((trade) => {
    trade.color = TRADE_COLOR_OVERRIDES[trade.key] ?? trade.color;
  });
});

export const ROLL_MS = 1060;
export const MOVE_STEP_MS = 325;
export const ROUND_PAUSE_MS = 625;
export const BASE_PROJECT_BUDGET = 200000;
export const BASE_PROJECT_DURATION = 30;
export const DAILY_DELAY_COST = 5000;
export const PUSH_COST = 5000;
export const LIQUIDATED_DAMAGES_PER_DAY = 10000;
export const ROADBLOCK_SPAWN_CHANCE = 0.28;
export const PERIOD_LABEL = "Day";
export const NAME_KEYS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
export const NAME_ACTIONS = ["SPACE", "DEL", "SAVE"];

export const MODES = [
  {
    name: "High Variability",
    dice: [1, 2, 3, 4, 5, 6],
    note: "Fast swings, rough planning",
  },
  {
    name: "Medium Variability",
    dice: [2, 3, 4, 5],
    note: "Balanced production",
  },
  { name: "Low Variability", dice: [3, 4], note: "Reliable takt rhythm" },
];
