export const PROJECTS = [
  {
    name: "Office Buildout",
    type: "office",
    levels: 3,
    zonesPerLevel: 6,
    budget: 3500000,
    duration: 100,
    dayPaceMultiplier: 2,
    costPaceMultiplier: 2,
    laborCostMultiplier: 0.408,
    roadblockChanceBonus: 0.05,
    summary: "Office building",
    trades: [
      { key: "framing", name: "Framing", color: "#7d8790", baseCost: 2625 },
      { key: "plumbing", name: "Plumbing", color: "#2388d1", baseCost: 2550 },
      {
        key: "electrical",
        name: "Electrical",
        color: "#f3c537",
        baseCost: 2520,
      },
      { key: "drywall", name: "Drywall", color: "#d8d2c6", baseCost: 2430 },
      { key: "painting", name: "Painting", color: "#78b7e8", baseCost: 2250 },
      { key: "finishes", name: "Finishes", color: "#55a85f", baseCost: 2775 },
    ],
  },
  {
    name: "Hospital Buildout",
    type: "hospital",
    levels: 4,
    zonesPerLevel: 6,
    budget: 23500000,
    duration: 255,
    dayPaceMultiplier: 1.75,
    costPaceMultiplier: 1.75,
    laborCostMultiplier: 0.442,
    summary: "Hospital project",
    trades: [
      { key: "framing", name: "Framing", color: "#7d8790", baseCost: 1850 },
      { key: "hvac", name: "HVAC", color: "#56c0c9", baseCost: 2050 },
      { key: "plumbing", name: "Plumbing", color: "#2388d1", baseCost: 1950 },
      {
        key: "fire",
        name: "Fire Protection",
        color: "#e84f3d",
        baseCost: 1900,
      },
      {
        key: "electrical",
        name: "Electrical",
        color: "#f3c537",
        baseCost: 1880,
      },
      { key: "drywall", name: "Drywall", color: "#d8d2c6", baseCost: 1720 },
      {
        key: "finishes",
        name: "Finishes",
        color: "#55a85f",
        baseCost: 2100,
      },
      {
        key: "equipment",
        name: "Equipment Install",
        color: "#b07ad8",
        baseCost: 2300,
      },
    ],
  },
  {
    name: "Wind Farm",
    type: "wind-farm",
    levels: 1,
    zonesPerLevel: 20,
    zoneColumns: 5,
    budget: 15000000,
    duration: 120,
    dayPaceMultiplier: 1.575,
    costPaceMultiplier: 1.75,
    laborCostMultiplier: 0.409,
    summary: "Wind farm field",
    trades: [
      {
        key: "survey-layout",
        visualKey: "site-inspection",
        name: "Survey and Layout",
        color: "#b9975b",
        baseCost: 1700,
      },
      {
        key: "earthwork",
        name: "Earthwork",
        color: "#9b7a4d",
        baseCost: 1800,
      },
      {
        key: "formwork-rebar",
        visualKey: "slab-foundation",
        name: "Formwork and Rebar",
        color: "#7c8188",
        baseCost: 1950,
      },
      {
        key: "electrical",
        name: "Electrical",
        color: "#ffcf4d",
        baseCost: 2050,
      },
      {
        key: "foundation",
        visualKey: "turbine-foundation",
        name: "Foundation",
        color: "#8d9298",
        baseCost: 2100,
      },
      {
        key: "tower-erection",
        name: "Tower Erection",
        color: "#d7dde4",
        baseCost: 2350,
      },
      {
        key: "nacelle-install",
        name: "Nacelle Installation",
        color: "#8bc4ff",
        baseCost: 2450,
      },
      {
        key: "blade-install",
        name: "Blade Installation",
        color: "#f5f7fb",
        baseCost: 2550,
      },
      {
        key: "wind-commissioning",
        name: "Commissioning",
        color: "#4ac77b",
        baseCost: 2200,
      },
    ],
  },
  {
    name: "Housing Development",
    type: "housing",
    levels: 1,
    zonesPerLevel: 20,
    zoneColumns: 5,
    budget: 24000000,
    duration: 240,
    dayPaceMultiplier: 1.6,
    costPaceMultiplier: 1.6,
    laborCostMultiplier: 0.467,
    summary: "Housing development",
    trades: [
      {
        key: "survey-layout",
        visualKey: "site-inspection",
        name: "Survey & Layout",
        color: "#b9975b",
        baseCost: 1700,
      },
      {
        key: "utilities",
        name: "Utilities",
        color: "#2f9dd6",
        baseCost: 1850,
      },
      {
        key: "foundations",
        visualKey: "slab-foundation",
        name: "Foundations",
        color: "#8d9298",
        baseCost: 2100,
      },
      {
        key: "framing",
        name: "Framing",
        color: "#c58a4a",
        baseCost: 2150,
      },
      { key: "roofing", name: "Roofing", color: "#7f4f3a", baseCost: 2050 },
      {
        key: "exterior-finishes",
        visualKey: "home-finishes",
        name: "Exterior Finishes",
        color: "#14b8a6",
        baseCost: 2000,
      },
      {
        key: "interior-finishes",
        visualKey: "finishes",
        name: "Interior Finishes",
        color: "#a855f7",
        baseCost: 2100,
      },
      {
        key: "landscaping",
        visualKey: "amenities",
        name: "Landscaping",
        color: "#22c55e",
        baseCost: 2150,
      },
      {
        key: "final-punchlist",
        visualKey: "final-inspection",
        name: "Final Punchlist",
        color: "#f43f5e",
        baseCost: 2250,
      },
    ],
  },
  {
    name: "Solar Farm",
    type: "solar-farm",
    levels: 1,
    zonesPerLevel: 30,
    zoneColumns: 6,
    budget: 12000000,
    duration: 210,
    dayPaceMultiplier: 1.25,
    costPaceMultiplier: 1.25,
    laborCostMultiplier: 0.54,
    summary: "Solar farm array",
    trades: [
      {
        key: "access-roads",
        name: "Access Roads",
        color: "#b9975b",
        baseCost: 1800,
      },
      {
        key: "pile-driving",
        name: "Pile Driving",
        color: "#8d9298",
        baseCost: 2050,
      },
      {
        key: "solar-racking",
        name: "Racking",
        color: "#6f8796",
        baseCost: 2150,
      },
      {
        key: "solar-panels",
        name: "Panel Install",
        color: "#1d5f9f",
        baseCost: 2300,
      },
      {
        key: "collection-cabling",
        name: "DC Cabling",
        color: "#ffcf4d",
        baseCost: 2050,
      },
      { key: "inverters", name: "Inverters", color: "#b583e8", baseCost: 2250 },
      {
        key: "grid-tie",
        name: "Grid Tie-In",
        color: "#ff8a2a",
        baseCost: 2350,
      },
      {
        key: "solar-commissioning",
        name: "Commissioning",
        color: "#4ac77b",
        baseCost: 2200,
      },
    ],
  },
  {
    name: "Industrial Plant",
    type: "industrial-plant",
    levels: 1,
    zonesPerLevel: 25,
    zoneColumns: 6,
    budget: 120000000,
    duration: 580,
    dayPaceMultiplier: 1.2,
    costPaceMultiplier: 1.2,
    laborCostMultiplier: 0.56,
    summary: "Industrial processing plant",
    trades: [
      {
        key: "below-grade-utilities",
        visualKey: "underground",
        name: "Below-Grade Utilities",
        color: "#0d9488",
        baseCost: 2050,
      },
      {
        key: "industrial-foundations",
        visualKey: "slab-foundation",
        name: "Foundations",
        color: "#78716c",
        baseCost: 2350,
      },
      {
        key: "structural-steel",
        visualKey: "structure",
        name: "Structural Steel",
        color: "#64748b",
        baseCost: 2450,
      },
      {
        key: "boilermakers-millwrights",
        visualKey: "equipment",
        name: "Boilermakers & Millwrights",
        color: "#f97316",
        baseCost: 2400,
      },
      {
        key: "pipe-fitters",
        visualKey: "process-piping",
        name: "Pipe Fitters",
        color: "#38bdf8",
        baseCost: 2350,
      },
      {
        key: "electrical-instrumentation",
        visualKey: "electrical",
        name: "Electrical & Instrumentation",
        color: "#facc15",
        baseCost: 2300,
      },
      {
        key: "insulation-cladding",
        visualKey: "finishes",
        name: "Insulation & Cladding",
        color: "#c084fc",
        baseCost: 2200,
      },
      {
        key: "industrial-commissioning",
        visualKey: "commissioning",
        name: "Commissioning",
        color: "#4ac77b",
        baseCost: 2300,
      },
    ],
  },
  {
    name: "Data Center",
    type: "data-center",
    levels: 1,
    zonesPerLevel: 30,
    zoneColumns: 6,
    budget: 650000000,
    duration: 420,
    dayPaceMultiplier: 1.15,
    costPaceMultiplier: 1.15,
    laborCostMultiplier: 0.564,
    summary: "Data center level",
    trades: [
      {
        key: "raised-floor",
        name: "Raised Floor",
        color: "#8a97a3",
        baseCost: 2100,
      },
      {
        key: "hvac",
        name: "HVAC",
        color: "#32c7dc",
        baseCost: 2350,
      },
      {
        key: "process-piping",
        name: "Process Piping",
        color: "#0ea5e9",
        baseCost: 2450,
      },
      {
        key: "fire",
        name: "Fire Protection",
        color: "#e84f3d",
        baseCost: 2250,
      },
      {
        key: "electrical",
        name: "Electrical",
        color: "#ffd84d",
        baseCost: 2050,
      },
      {
        key: "containment",
        name: "Containment",
        color: "#4f6170",
        baseCost: 2200,
      },
      {
        key: "finishes",
        name: "Finishes",
        color: "#2fd17c",
        baseCost: 2400,
      },
      {
        key: "equipment",
        name: "Equipment",
        color: "#d66dff",
        baseCost: 2550,
      },
    ],
  },
];

const TRADE_COLOR_OVERRIDES = {
  framing: "#6B7280",
  plumbing: "#2563EB",
  electrical: "#FACC15",
  drywall: "#D8DEE9",
  painting: "#38BDF8",
  finishes: "#22C55E",
  hvac: "#14B8A6",
  "process-piping": "#0EA5E9",
  fire: "#EF4444",
  cleanroom: "#A7F3D0",
  equipment: "#A855F7",
  "raised-floor": "#94A3B8",
  power: "#F59E0B",
  "backup-power": "#EA580C",
  cooling: "#0EA5E9",
  "data-cabling": "#6366F1",
  "rack-install": "#334155",
  "server-equipment": "#10B981",
  containment: "#334155",
  commissioning: "#D946EF",
  "access-roads": "#A16207",
  "turbine-foundation": "#64748B",
  "tower-erection": "#CBD5E1",
  "nacelle-install": "#60A5FA",
  "blade-install": "#F8FAFC",
  "collection-cabling": "#EAB308",
  substation: "#8B5CF6",
  "wind-commissioning": "#84CC16",
  sitework: "#CA8A04",
  utilities: "#06B6D4",
  "slab-foundation": "#78716C",
  "house-framing": "#B45309",
  roofing: "#7C2D12",
  "mep-rough": "#FDE047",
  "home-finishes": "#4ADE80",
  excavation: "#92400E",
  foundation: "#78716C",
  foundations: "#78716C",
  "dry-in": "#E5E7EB",
  siding: "#A8A29E",
  "driveway-utilities": "#38BDF8",
  "exterior-finishes": "#E5E7EB",
  "interior-finishes": "#A8A29E",
  landscaping: "#4ADE80",
  "completed-home": "#22C55E",
  "final-punchlist": "#22C55E",
  "pile-driving": "#71717A",
  "solar-racking": "#0891B2",
  "solar-panels": "#1D4ED8",
  inverters: "#C084FC",
  "grid-tie": "#FB923C",
  "solar-commissioning": "#65A30D",
  earthwork: "#92400E",
  "below-grade-utilities": "#0D9488",
  "industrial-foundations": "#78716C",
  "structural-steel": "#64748B",
  "boilermakers-millwrights": "#F97316",
  "pipe-fitters": "#38BDF8",
  "electrical-instrumentation": "#FACC15",
  "insulation-cladding": "#C084FC",
  "industrial-commissioning": "#16A34A",
  underground: "#0F766E",
  "deep-foundations": "#57534E",
  waterproofing: "#0284C7",
  "utility-tie": "#FB7185",
  "site-inspection": "#15803D",
  structure: "#374151",
  skin: "#2DD4BF",
  elevators: "#7C3AED",
  "skin-inspection": "#059669",
  "guestroom-mep": "#FBBF24",
  tile: "#67E8F9",
  "ff-e": "#86EFAC",
  amenities: "#F97316",
  "final-inspection": "#4D7C0F",
};

PROJECTS.forEach((project) => {
  project.trades.forEach((trade) => {
    trade.color = TRADE_COLOR_OVERRIDES[trade.key] ?? trade.color;
  });
});

export const ROLL_MS = 2000;
export const MOVE_STEP_MS = 325;
export const ROUND_PAUSE_MS = 625;
export const BASE_PROJECT_BUDGET = 200000;
export const BASE_PROJECT_DURATION = 30;
export const DAILY_DELAY_COST = 5000;
export const PUSH_COST = 2500;
export const LIQUIDATED_DAMAGES_PER_DAY = 10000;
export const ROADBLOCK_SPAWN_CHANCE = 0.28;
export const PERIOD_LABEL = "Day";
export const NAME_KEYS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
export const NAME_ACTIONS = ["SPACE", "DEL", "SAVE"];

export const MODES = [
  {
    name: "Low Variability",
    dice: [3, 4],
    note: "Reliable takt rhythm",
    maxProfitMargin: 0.5,
  },
  {
    name: "Medium Variability",
    dice: [2, 3, 4, 5],
    note: "Balanced production",
  },
  {
    name: "High Variability",
    dice: [1, 2, 3, 4, 5, 6],
    note: "Fast swings, rough planning",
  },
];
