export const PROJECTS = [
  {
    name: "Office Building",
    type: "office",
    levels: 3,
    zonesPerLevel: 6,
    summary: "Office building",
    trades: [
      { key: "framing", name: "Framing", color: "#7d8790", baseCost: 1750 },
      { key: "plumbing", name: "Plumbing", color: "#2388d1", baseCost: 1700 },
      {
        key: "electrical",
        name: "Electrical",
        color: "#f3c537",
        baseCost: 1680,
      },
      { key: "drywall", name: "Drywall", color: "#d8d2c6", baseCost: 1620 },
      { key: "painting", name: "Painting", color: "#78b7e8", baseCost: 1500 },
      { key: "finishes", name: "Finishes", color: "#55a85f", baseCost: 1850 },
    ],
  },
  {
    name: "Hospital Buildout",
    type: "hospital",
    levels: 4,
    zonesPerLevel: 6,
    summary: "Hospital project",
    trades: [
      { key: "framing", name: "Framing", color: "#7d8790", baseCost: 1850 },
      { key: "hvac", name: "HVAC", color: "#56c0c9", baseCost: 2050 },
      { key: "plumbing", name: "Plumbing", color: "#2388d1", baseCost: 1950 },
      {
        key: "fire",
        name: "Fire Protection",
        color: "#e84f3d",
        baseCost: 1900,
      },
      {
        key: "electrical",
        name: "Electrical",
        color: "#f3c537",
        baseCost: 1880,
      },
      { key: "drywall", name: "Drywall", color: "#d8d2c6", baseCost: 1720 },
      {
        key: "finishes",
        name: "Finishes",
        color: "#55a85f",
        baseCost: 2100,
      },
      {
        key: "equipment",
        name: "Equipment Install",
        color: "#b07ad8",
        baseCost: 2300,
      },
    ],
  },
  {
    name: "Data Center",
    type: "data-center",
    levels: 1,
    zonesPerLevel: 30,
    zoneColumns: 6,
    summary: "Data center level",
    trades: [
      {
        key: "raised-floor",
        name: "Raised Floor",
        color: "#8a97a3",
        baseCost: 2100,
      },
      {
        key: "hvac",
        name: "HVAC",
        color: "#32c7dc",
        baseCost: 2350,
      },
      {
        key: "process-piping",
        name: "Process Piping",
        color: "#0ea5e9",
        baseCost: 2450,
      },
      {
        key: "fire",
        name: "Fire Protection",
        color: "#e84f3d",
        baseCost: 2250,
      },
      {
        key: "electrical",
        name: "Electrical",
        color: "#ffd84d",
        baseCost: 2050,
      },
      {
        key: "containment",
        name: "Containment",
        color: "#4f6170",
        baseCost: 2200,
      },
      {
        key: "finishes",
        name: "Finishes",
        color: "#2fd17c",
        baseCost: 2400,
      },
      {
        key: "equipment",
        name: "Equipment",
        color: "#d66dff",
        baseCost: 2550,
      },
    ],
  },
  {
    name: "Wind Farm",
    type: "wind-farm",
    levels: 1,
    zonesPerLevel: 20,
    zoneColumns: 5,
    summary: "Wind farm field",
    trades: [
      {
        key: "survey-layout",
        name: "Survey and Layout",
        color: "#b9975b",
        baseCost: 1700,
      },
      {
        key: "earthwork",
        name: "Earthwork",
        color: "#9b7a4d",
        baseCost: 1800,
      },
      {
        key: "formwork-rebar",
        name: "Formwork and Rebar",
        color: "#7c8188",
        baseCost: 1950,
      },
      {
        key: "electrical",
        name: "Electrical",
        color: "#ffcf4d",
        baseCost: 2050,
      },
      {
        key: "foundation",
        name: "Foundation",
        color: "#8d9298",
        baseCost: 2100,
      },
      {
        key: "tower-erection",
        name: "Tower Erection",
        color: "#d7dde4",
        baseCost: 2350,
      },
      {
        key: "nacelle-install",
        name: "Nacelle Installation",
        color: "#8bc4ff",
        baseCost: 2450,
      },
      {
        key: "blade-install",
        name: "Blade Installation",
        color: "#f5f7fb",
        baseCost: 2550,
      },
      {
        key: "wind-commissioning",
        name: "Commissioning",
        color: "#4ac77b",
        baseCost: 2200,
      },
    ],
  },
  {
    name: "Housing Development",
    type: "housing",
    levels: 1,
    zonesPerLevel: 20,
    zoneColumns: 5,
    summary: "Housing development",
    trades: [
      { key: "sitework", name: "Sitework", color: "#9b7a4d", baseCost: 1900 },
      { key: "utilities", name: "Utilities", color: "#2f9dd6", baseCost: 2000 },
      {
        key: "slab-foundation",
        name: "Slab Foundations",
        color: "#8d9298",
        baseCost: 2100,
      },
      {
        key: "house-framing",
        name: "House Framing",
        color: "#c58a4a",
        baseCost: 2150,
      },
      { key: "roofing", name: "Roofing", color: "#7f4f3a", baseCost: 2050 },
      {
        key: "mep-rough",
        name: "MEP Rough-In",
        color: "#f3c537",
        baseCost: 2200,
      },
      { key: "drywall", name: "Drywall", color: "#d8d2c6", baseCost: 1900 },
      {
        key: "home-finishes",
        name: "Home Finishes",
        color: "#6bbf6f",
        baseCost: 2250,
      },
    ],
  },
  {
    name: "Solar Farm",
    type: "solar-farm",
    levels: 1,
    zonesPerLevel: 30,
    zoneColumns: 6,
    summary: "Solar farm array",
    trades: [
      {
        key: "access-roads",
        name: "Access Roads",
        color: "#b9975b",
        baseCost: 1800,
      },
      {
        key: "pile-driving",
        name: "Pile Driving",
        color: "#8d9298",
        baseCost: 2050,
      },
      {
        key: "solar-racking",
        name: "Racking",
        color: "#6f8796",
        baseCost: 2150,
      },
      {
        key: "solar-panels",
        name: "Panel Install",
        color: "#1d5f9f",
        baseCost: 2300,
      },
      {
        key: "collection-cabling",
        name: "DC Cabling",
        color: "#ffcf4d",
        baseCost: 2050,
      },
      { key: "inverters", name: "Inverters", color: "#b583e8", baseCost: 2250 },
      {
        key: "grid-tie",
        name: "Grid Tie-In",
        color: "#ff8a2a",
        baseCost: 2350,
      },
      {
        key: "solar-commissioning",
        name: "Commissioning",
        color: "#4ac77b",
        baseCost: 2200,
      },
    ],
  },
  {
    name: "Airport Expansion",
    type: "airport",
    levels: 1,
    zonesPerLevel: 25,
    zoneColumns: 5,
    summary: "Airport expansion",
    trades: [
      { key: "earthwork", name: "Earthwork", color: "#9b7a4d", baseCost: 2050 },
      {
        key: "paving",
        name: "Runway Paving",
        color: "#5a6066",
        baseCost: 2350,
      },
      {
        key: "terminal-structure",
        name: "Terminal Structure",
        color: "#7d8790",
        baseCost: 2450,
      },
      {
        key: "baggage",
        name: "Baggage Systems",
        color: "#32c7dc",
        baseCost: 2250,
      },
      {
        key: "jet-bridges",
        name: "Jet Bridges",
        color: "#8bc4ff",
        baseCost: 2400,
      },
      {
        key: "electrical",
        name: "Airfield Electrical",
        color: "#f3c537",
        baseCost: 2300,
      },
      {
        key: "security-systems",
        name: "Security Systems",
        color: "#d66dff",
        baseCost: 2200,
      },
      {
        key: "airport-commissioning",
        name: "Commissioning",
        color: "#4ac77b",
        baseCost: 2300,
      },
    ],
  },
  {
    name: "Hotel Sitework",
    type: "hotel-site",
    levels: 1,
    zonesPerLevel: 24,
    zoneColumns: 6,
    summary: "Hotel dirt work, utilities, and foundations",
    trades: [
      { key: "earthwork", name: "Dirt Work", color: "#9b7a4d", baseCost: 2150 },
      {
        key: "underground",
        name: "Underground Utilities",
        color: "#2388d1",
        baseCost: 2250,
      },
      {
        key: "deep-foundations",
        name: "Deep Foundations",
        color: "#8d9298",
        baseCost: 2450,
      },
      {
        key: "slab-foundation",
        name: "Grade Beams / Slabs",
        color: "#b8bcc0",
        baseCost: 2350,
      },
      {
        key: "waterproofing",
        name: "Waterproofing",
        color: "#32c7dc",
        baseCost: 2100,
      },
      {
        key: "utility-tie",
        name: "Utility Tie-Ins",
        color: "#f3c537",
        baseCost: 2250,
      },
      {
        key: "site-inspection",
        name: "Site Inspection",
        color: "#4ac77b",
        baseCost: 2000,
      },
    ],
  },
  {
    name: "Hotel Structure and Skin",
    type: "hotel-structure",
    levels: 6,
    zonesPerLevel: 6,
    summary: "Hotel structure and skin",
    trades: [
      { key: "structure", name: "Structure", color: "#7d8790", baseCost: 2450 },
      { key: "skin", name: "Exterior Skin", color: "#78b7e8", baseCost: 2350 },
      { key: "roofing", name: "Roofing", color: "#7f4f3a", baseCost: 2200 },
      { key: "elevators", name: "Elevators", color: "#b583e8", baseCost: 2550 },
      {
        key: "mep-rough",
        name: "MEP Risers",
        color: "#f3c537",
        baseCost: 2400,
      },
      {
        key: "fire",
        name: "Fire Protection",
        color: "#e84f3d",
        baseCost: 2250,
      },
      {
        key: "skin-inspection",
        name: "Envelope Inspection",
        color: "#4ac77b",
        baseCost: 2050,
      },
    ],
  },
  {
    name: "Hotel Interior Finishes",
    type: "hotel-interiors",
    levels: 6,
    zonesPerLevel: 6,
    summary: "Hotel interior finishes",
    trades: [
      {
        key: "framing",
        name: "Interior Framing",
        color: "#7d8790",
        baseCost: 2150,
      },
      {
        key: "guestroom-mep",
        name: "Guestroom MEP",
        color: "#f3c537",
        baseCost: 2350,
      },
      { key: "drywall", name: "Drywall", color: "#d8d2c6", baseCost: 2050 },
      { key: "tile", name: "Tile / Baths", color: "#78b7e8", baseCost: 2250 },
      {
        key: "painting",
        name: "Paint / Wallcovering",
        color: "#b8a5e6",
        baseCost: 2050,
      },
      { key: "ff-e", name: "FF&E", color: "#6bbf6f", baseCost: 2450 },
      { key: "amenities", name: "Amenities", color: "#ffcf4d", baseCost: 2350 },
      {
        key: "final-inspection",
        name: "Final Inspection",
        color: "#4ac77b",
        baseCost: 2150,
      },
    ],
  },
];

const TRADE_COLOR_OVERRIDES = {
  framing: "#6B7280",
  plumbing: "#2563EB",
  electrical: "#FACC15",
  drywall: "#D8DEE9",
  painting: "#38BDF8",
  finishes: "#22C55E",
  hvac: "#14B8A6",
  "process-piping": "#0EA5E9",
  fire: "#EF4444",
  cleanroom: "#A7F3D0",
  equipment: "#A855F7",
  "raised-floor": "#94A3B8",
  power: "#F59E0B",
  "backup-power": "#EA580C",
  cooling: "#0EA5E9",
  "data-cabling": "#6366F1",
  "rack-install": "#334155",
  "server-equipment": "#10B981",
  containment: "#334155",
  commissioning: "#D946EF",
  "access-roads": "#A16207",
  "turbine-foundation": "#64748B",
  "tower-erection": "#CBD5E1",
  "nacelle-install": "#60A5FA",
  "blade-install": "#F8FAFC",
  "collection-cabling": "#EAB308",
  substation: "#8B5CF6",
  "wind-commissioning": "#84CC16",
  sitework: "#CA8A04",
  utilities: "#06B6D4",
  "slab-foundation": "#78716C",
  "house-framing": "#B45309",
  roofing: "#7C2D12",
  "mep-rough": "#FDE047",
  "home-finishes": "#4ADE80",
  "pile-driving": "#71717A",
  "solar-racking": "#0891B2",
  "solar-panels": "#1D4ED8",
  inverters: "#C084FC",
  "grid-tie": "#FB923C",
  "solar-commissioning": "#65A30D",
  earthwork: "#92400E",
  paving: "#52525B",
  "terminal-structure": "#475569",
  baggage: "#0D9488",
  "jet-bridges": "#93C5FD",
  "runway-lighting": "#FCD34D",
  "security-systems": "#E879F9",
  "systems-testing": "#F472B6",
  "airport-commissioning": "#16A34A",
  underground: "#0F766E",
  "deep-foundations": "#57534E",
  waterproofing: "#0284C7",
  "utility-tie": "#FB7185",
  "site-inspection": "#15803D",
  structure: "#374151",
  skin: "#2DD4BF",
  elevators: "#7C3AED",
  "skin-inspection": "#059669",
  "guestroom-mep": "#FBBF24",
  tile: "#67E8F9",
  "ff-e": "#86EFAC",
  amenities: "#F97316",
  "final-inspection": "#4D7C0F",
};

PROJECTS.forEach((project) => {
  project.trades.forEach((trade) => {
    trade.color = TRADE_COLOR_OVERRIDES[trade.key] ?? trade.color;
  });
});

export const ROLL_MS = 1060;
export const MOVE_STEP_MS = 325;
export const ROUND_PAUSE_MS = 625;
export const BASE_PROJECT_BUDGET = 200000;
export const BASE_PROJECT_DURATION = 30;
export const DAILY_DELAY_COST = 5000;
export const PUSH_COST = 2500;
export const LIQUIDATED_DAMAGES_PER_DAY = 10000;
export const ROADBLOCK_SPAWN_CHANCE = 0.28;
export const PERIOD_LABEL = "Day";
export const NAME_KEYS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
export const NAME_ACTIONS = ["SPACE", "DEL", "SAVE"];

export const MODES = [
  {
    name: "High Variability",
    dice: [1, 2, 3, 4, 5, 6],
    note: "Fast swings, rough planning",
  },
  {
    name: "Medium Variability",
    dice: [2, 3, 4, 5],
    note: "Balanced production",
  },
  { name: "Low Variability", dice: [3, 4], note: "Reliable takt rhythm" },
];
