export const INPUT_ACTIONS = Object.freeze({
  UP: "UP",
  DOWN: "DOWN",
  LEFT: "LEFT",
  RIGHT: "RIGHT",
  LOW_VARIABILITY: "LOW_VARIABILITY",
  MEDIUM_VARIABILITY: "MEDIUM_VARIABILITY",
  HIGH_VARIABILITY: "HIGH_VARIABILITY",
  REMOVE_ROADBLOCK: "REMOVE_ROADBLOCK",
  PUSH_TRADE: "PUSH_TRADE",
  IDENTIFY_ROADBLOCKS: "IDENTIFY_ROADBLOCKS",
  START: "START",
  BACK: "BACK",
});

export const PLAYER_ACTION_SEQUENCE = [
  INPUT_ACTIONS.UP,
  INPUT_ACTIONS.DOWN,
  INPUT_ACTIONS.LEFT,
  INPUT_ACTIONS.RIGHT,
  INPUT_ACTIONS.LOW_VARIABILITY,
  INPUT_ACTIONS.MEDIUM_VARIABILITY,
  INPUT_ACTIONS.HIGH_VARIABILITY,
  INPUT_ACTIONS.REMOVE_ROADBLOCK,
  INPUT_ACTIONS.PUSH_TRADE,
  INPUT_ACTIONS.IDENTIFY_ROADBLOCKS,
  INPUT_ACTIONS.START,
  INPUT_ACTIONS.BACK,
];

export const ACTION_LABELS = Object.freeze({
  [INPUT_ACTIONS.UP]: "Joystick Up",
  [INPUT_ACTIONS.DOWN]: "Joystick Down",
  [INPUT_ACTIONS.LEFT]: "Joystick Left",
  [INPUT_ACTIONS.RIGHT]: "Joystick Right",
  [INPUT_ACTIONS.LOW_VARIABILITY]: "Low Variability",
  [INPUT_ACTIONS.MEDIUM_VARIABILITY]: "Medium Variability",
  [INPUT_ACTIONS.HIGH_VARIABILITY]: "High Variability",
  [INPUT_ACTIONS.REMOVE_ROADBLOCK]: "Remove Roadblock",
  [INPUT_ACTIONS.PUSH_TRADE]: "Push Trade",
  [INPUT_ACTIONS.IDENTIFY_ROADBLOCKS]: "Identify Roadblocks",
  [INPUT_ACTIONS.START]: "Start / Join",
  [INPUT_ACTIONS.BACK]: "Escape / Back",
});

export const PLAYER_COUNT = 2;
export const AXIS_PRESS_THRESHOLD = 0.65;
export const AXIS_NEUTRAL_THRESHOLD = 0.35;

